### ISSUE TITLE
控制器无法销毁

### ISSUE THREAD

**Issue by lixianhong1992** [beforeold/GSNoticeManager#1]
当block中有self时，必须使用weakSelf ，控制器才能销毁。

**Comment by beforeold** [comment]
这个是有weak-strong 是必要的，因为并没有标记具体是哪个对象进行监听，也就无从直接决定何时销毁 block。

自 iOS 9 之后以 selector 进行的通知监听可以不再需要 remove 了，建议直接使用系统 NotificationCenter 的 selector 方式。
